sudo: false
language: node_js
services: mongodb
node_js:
  - '8'
install:
  - npm i npminstall && npminstall
before_script:
  - sleep 5
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
